name: Video Club CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.14

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Inicializar Base de Datos (Opcional)
      run: |
        # Solo si tus tests necesitan que la DB exista físicamente antes
        python database/init_db.py

    - name: Ejecutar Tests con Pytest
      run: |
        pytest